version: '3'

services:
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: movie_user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: movie_catalog
    volumes:
        - ./var/cache/mysql:/var/lib/mysql
